name: Release to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21 and Configure Maven for GitHub Packages
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github
        settings-path: ${{ github.workspace }}/settings.xml

    - name: Update pom.xml with repository info
      run: |
        REPO_OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
        sed -i "s/OWNER/$REPO_OWNER/g" pom.xml

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages
      run: mvn deploy -s ${{ github.workspace }}/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
