name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Semantic Release
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 21
        if: steps.semantic_release.outputs.new_release_published == 'true'
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Update pom.xml to next development version (-SNAPSHOT)
        if: steps.semantic_release.outputs.new_release_published == 'true'
        run: |
          NEW_DEV_VERSION="${{ steps.semantic_release.outputs.new_release_version }}-SNAPSHOT"
          ./mvnw -B versions:set -DgenerateBackupPoms=false -DnewVersion="$NEW_DEV_VERSION"

      - name: Commit and push updated pom.xml
        if: steps.semantic_release.outputs.new_release_published == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          if git diff --cached --quiet; then
            echo "No pom.xml changes to commit"
          else
            git commit -m "chore(release): set next development version to ${{ steps.semantic_release.outputs.new_release_version }}-SNAPSHOT [skip ci]"
            git push
          fi
